// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Signal struct {
	ID         int64              `json:"id"`
	Type       string             `json:"type"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	Company    pgtype.Text        `json:"company"`
	Service    pgtype.Text        `json:"service"`
	Message    string             `json:"message"`
	SourcePage pgtype.Text        `json:"source_page"`
	Locale     string             `json:"locale"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Visit struct {
	ID        int64              `json:"id"`
	Path      string             `json:"path"`
	Locale    string             `json:"locale"`
	Referrer  pgtype.Text        `json:"referrer"`
	UserAgent pgtype.Text        `json:"user_agent"`
	VisitedAt pgtype.Timestamptz `json:"visited_at"`
}
