// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountSignalsByType(ctx context.Context) ([]CountSignalsByTypeRow, error)
	CreateSignal(ctx context.Context, arg CreateSignalParams) (Signal, error)
	CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error)
	ListSignals(ctx context.Context) ([]Signal, error)
	TotalVisits(ctx context.Context) (int64, error)
	VisitsByPath(ctx context.Context, limit int32) ([]VisitsByPathRow, error)
}

var _ Querier = (*Queries)(nil)
