// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignalsByType = `-- name: CountSignalsByType :many
SELECT type, COUNT(*) AS total
FROM signals
GROUP BY type
`

type CountSignalsByTypeRow struct {
	Type  string `json:"type"`
	Total int64  `json:"total"`
}

func (q *Queries) CountSignalsByType(ctx context.Context) ([]CountSignalsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countSignalsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSignalsByTypeRow
	for rows.Next() {
		var i CountSignalsByTypeRow
		if err := rows.Scan(&i.Type, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSignal = `-- name: CreateSignal :one
INSERT INTO signals (type, name, email, company, service, message, source_page, locale)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, type, name, email, company, service, message, source_page, locale, created_at
`

type CreateSignalParams struct {
	Type       string      `json:"type"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Company    pgtype.Text `json:"company"`
	Service    pgtype.Text `json:"service"`
	Message    string      `json:"message"`
	SourcePage pgtype.Text `json:"source_page"`
	Locale     string      `json:"locale"`
}

func (q *Queries) CreateSignal(ctx context.Context, arg CreateSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, createSignal,
		arg.Type,
		arg.Name,
		arg.Email,
		arg.Company,
		arg.Service,
		arg.Message,
		arg.SourcePage,
		arg.Locale,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Email,
		&i.Company,
		&i.Service,
		&i.Message,
		&i.SourcePage,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (path, locale, referrer, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, path, locale, referrer, user_agent, visited_at
`

type CreateVisitParams struct {
	Path      string      `json:"path"`
	Locale    string      `json:"locale"`
	Referrer  pgtype.Text `json:"referrer"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.Path,
		arg.Locale,
		arg.Referrer,
		arg.UserAgent,
	)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Locale,
		&i.Referrer,
		&i.UserAgent,
		&i.VisitedAt,
	)
	return i, err
}

const listSignals = `-- name: ListSignals :many
SELECT id, type, name, email, company, service, message, source_page, locale, created_at
FROM signals
ORDER BY created_at DESC
`

func (q *Queries) ListSignals(ctx context.Context) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listSignals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signal
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.Service,
			&i.Message,
			&i.SourcePage,
			&i.Locale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalVisits = `-- name: TotalVisits :one
SELECT COUNT(*) AS total
FROM visits
`

func (q *Queries) TotalVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalVisits)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const visitsByPath = `-- name: VisitsByPath :many
SELECT path, COUNT(*) AS total
FROM visits
GROUP BY path
ORDER BY total DESC
LIMIT $1
`

type VisitsByPathRow struct {
	Path  string `json:"path"`
	Total int64  `json:"total"`
}

func (q *Queries) VisitsByPath(ctx context.Context, limit int32) ([]VisitsByPathRow, error) {
	rows, err := q.db.Query(ctx, visitsByPath, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisitsByPathRow
	for rows.Next() {
		var i VisitsByPathRow
		if err := rows.Scan(&i.Path, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
